packages:
  - .

strictDepBuilds: false

allowBuilds:
  '@napi-rs/canvas': true
  better-sqlite3: true
  ffmpeg-static: true

overrides:
  lodash: ^4.17.23
  '@xmldom/xmldom': ^0.9.8
  '@types/localforage': npm:empty-module@0.0.2
